blank_issues_enabled: false
contact_links:
  - name: Homebridge Discord Channel for Honeywell-Home
    url: https://discord.gg/8fpZA4S
    about: Please ask and answer questions here.
  - name: Homebridge-Honeywell-Home - Pull Requests
    url: https://github.com/homebridge-plugins/homebridge-honeywell-home/pulls
    about: Please report security vulnerabilities here.
